* Tools, toys and experiments for PICO-8
  Each directory is a separate tool with its own README explaining how
  to use it and, in most cases, a ~demos~ directory showing the tool
  in use.

** ~stream-ecs~ 267 Tokens
   A small Entity-Component-System framework based on reactive streams. 
   
** ~prot-oo~  72 Tokens
   Prototype based object-oriented programming based, roughly, on
   javascript's OO model.

** ~string-gram~ 104 Tokens
   Functions for creating context-free generative string grammars.

** ~jump-tuner~
   An interactive tool for tuning jump behaviour.

** ~state-machines~ 107/111 Tokens
   Two slightly different implementations of a state machine manager.

   
   
* License note
  Due to the strict character limit of PICO-8 cartridges, it is not
  necessary to include the full license text in the source files
  themselves. Providing the copyright notice and the url to the full
  license
  (https://github.com/jasondelaat/pico8-tools/blob/release/LICENSE) is
  sufficient.

   
